name = input("Enter your name ")
siblingbirthday = input("Enter sibling birthday (Leave blank if none) ")
mombirthday = input("Enter mom birthday (Leave blank if none) ")
dadbirthday = input("Enter dad birthday (Leave blank if none) ")
Birthday = input("Enter birthday ")
print("Hello", name,  "I will remember your birthday which is ", Birthday, ", I will also remember your family's birthdays like your dads:", dadbirthday, "also your moms", mombirthday, "and your sibling", siblingbirthday)
